name: Deploy CHelper-Web to my server

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/deploy-web.yml'
      - 'CHelper-Web/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - '.github/workflows/deploy-web.yml'
      - 'CHelper-Web/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          cache: true

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          cache: 'pnpm'
          cache-dependency-path: 'CHelper-Web/pnpm-lock.yaml'

      - name: Install dependencies
        working-directory: ${{ github.workspace }}/CHelper-Web
        run: pnpm install

      - name: Build
        working-directory: ${{ github.workspace }}/CHelper-Web
        run: npx vite build --base=/chelper/ --mode my_server
  
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "CHelper-Web/dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.CHELPER_WEB_TARGET }}
